# Generated by Django 2.1.7 on 2019-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='code',
        ),
        migrations.RemoveField(
            model_name='source',
            name='comment',
        ),
        migrations.AddField(
            model_name='source',
            name='text',
            field=models.TextField(blank=True, verbose_name='テキストエリア'),
        ),
    ]
