# Generated by Django 2.1.7 on 2019-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcebook', '0002_auto_20190828_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='text_flg',
            field=models.IntegerField(default=0, verbose_name='テキストフラグ'),
            preserve_default=False,
        ),
    ]
